language: python

before_install:
  - pip install pylint matplotlib

script:
  - pylint -rn -sn mpl_plot.py
  - python -c 'from mpl_plot import *'

notifications:
  email:
    on_success: never
    on_failure: always
